# Generated by Django 5.2.8 on 2025-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
