# Generated by Django 5.2.8 on 2025-12-01 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_rename_events_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('rsvp_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')])),
                ('check_in_time', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
